project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Gulf Temperature's Effect on Power Plant"
  author: "Grey Gergen"
  page-footer:
    left: "Copyright 2025, Grey Gergen"
  chapters:
    - index.qmd
    - executive-summary.qmd
    - report.qmd
    - references.qmd
    - part: "Appendices"
      chapters:
        - data-documentation.qmd
    - part: "Drafts"
      chapters:
        - draft-data-doc.qmd
        - draft-results.qmd
        - draft-intro-conclusions.qmd
        - draft-exec-summary.qmd



bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    latex-engine: xelatex
    documentclass: scrreprt



