---
title: "Draft: Intro/Conclusions"
---

# Intro

Many power plants rely on water for cooling the plant and keeping it stable. The issue with the power plant that is being assessed, located in Dauphin Island, Alabama, is that it uses water from the Gulf of Mexico. Now if a power plant uses the water to cool down the reactor then you would want that water to be as cold as possible right? When the plant being examined was built, it was assumed the temperature of the water extracted from the gulf would not exceed 85 degrees Fahrenheit because if it did the plant would have to operate at reduced capacity. With ocean temperatures rising it is necessary to find out if the plant can remain at capacity. Using ocean temperature and energy demand data this analysis looks into the risk of operating the plant at reduced capacity and when the energy from the plant is needed most.

# Conclusion

From the analysis we can see that the rising temperature of the water from the Gulf of Mexico is consistently exceeding the limit of 85 degrees Fahrenheit set by the plant, especially during the peak summer months of July and August. We can only assume the number of days where the water is above the threshold is to increase due to rising ocean temperatures. Based upon recent electrical usage data we see that those warm months are the highest for electrical usage. The plant being forced to operate at reduction during the warm months coupled with the fact that those months are the highest in demand for energy show that a solution is necessary for the plant to remain at full operation. 